/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as DashboardTrashRouteImport } from './routes/dashboard.trash'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSharedRouteImport } from './routes/dashboard.shared'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRecentRouteImport } from './routes/dashboard.recent'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardFilesRouteImport } from './routes/dashboard.files'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as ApiSharesRouteImport } from './routes/api/shares'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as ApiSharesTokenRouteImport } from './routes/api/shares.$token'
import { Route as ApiFilesIdRouteImport } from './routes/api/files.$id'
import { Route as AuthSignupSsoCallbackRouteImport } from './routes/_auth.signup.sso-callback'
import { Route as AuthLoginSsoCallbackRouteImport } from './routes/_auth.login.sso-callback'
import { Route as ApiFilesIdDownloadRouteImport } from './routes/api/files.$id.download'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSharedRoute = DashboardSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecentRoute = DashboardRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSharesTokenRoute = ApiSharesTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ApiSharesRoute,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFilesRoute,
} as any)
const AuthSignupSsoCallbackRoute = AuthSignupSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => AuthSignupRoute,
} as any)
const AuthLoginSsoCallbackRoute = AuthLoginSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => AuthLoginRoute,
} as any)
const ApiFilesIdDownloadRoute = ApiFilesIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiFilesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/signup': typeof AuthSignupRouteWithChildren
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/sso-callback': typeof AuthLoginSsoCallbackRoute
  '/signup/sso-callback': typeof AuthSignupSsoCallbackRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/files/$id/download': typeof ApiFilesIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/signup': typeof AuthSignupRouteWithChildren
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login/sso-callback': typeof AuthLoginSsoCallbackRoute
  '/signup/sso-callback': typeof AuthSignupSsoCallbackRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/files/$id/download': typeof ApiFilesIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_auth/login': typeof AuthLoginRouteWithChildren
  '/_auth/signup': typeof AuthSignupRouteWithChildren
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_auth/login/sso-callback': typeof AuthLoginSsoCallbackRoute
  '/_auth/signup/sso-callback': typeof AuthSignupSsoCallbackRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/files/$id/download': typeof ApiFilesIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/playground'
    | '/sso-callback'
    | '/login'
    | '/signup'
    | '/api/files'
    | '/api/shares'
    | '/dashboard/favorites'
    | '/dashboard/files'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/settings'
    | '/dashboard/shared'
    | '/dashboard/team'
    | '/dashboard/trash'
    | '/share/$token'
    | '/dashboard/'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/api/files/$id'
    | '/api/shares/$token'
    | '/api/files/$id/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/sso-callback'
    | '/login'
    | '/signup'
    | '/api/files'
    | '/api/shares'
    | '/dashboard/favorites'
    | '/dashboard/files'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/settings'
    | '/dashboard/shared'
    | '/dashboard/team'
    | '/dashboard/trash'
    | '/share/$token'
    | '/dashboard'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/api/files/$id'
    | '/api/shares/$token'
    | '/api/files/$id/download'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/playground'
    | '/sso-callback'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/files'
    | '/api/shares'
    | '/dashboard/favorites'
    | '/dashboard/files'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/settings'
    | '/dashboard/shared'
    | '/dashboard/team'
    | '/dashboard/trash'
    | '/share/$token'
    | '/dashboard/'
    | '/_auth/login/sso-callback'
    | '/_auth/signup/sso-callback'
    | '/api/files/$id'
    | '/api/shares/$token'
    | '/api/files/$id/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiSharesRoute: typeof ApiSharesRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shared': {
      id: '/dashboard/shared'
      path: '/shared'
      fullPath: '/dashboard/shared'
      preLoaderRoute: typeof DashboardSharedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recent': {
      id: '/dashboard/recent'
      path: '/recent'
      fullPath: '/dashboard/recent'
      preLoaderRoute: typeof DashboardRecentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/shares/$token': {
      id: '/api/shares/$token'
      path: '/$token'
      fullPath: '/api/shares/$token'
      preLoaderRoute: typeof ApiSharesTokenRouteImport
      parentRoute: typeof ApiSharesRoute
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/_auth/signup/sso-callback': {
      id: '/_auth/signup/sso-callback'
      path: '/sso-callback'
      fullPath: '/signup/sso-callback'
      preLoaderRoute: typeof AuthSignupSsoCallbackRouteImport
      parentRoute: typeof AuthSignupRoute
    }
    '/_auth/login/sso-callback': {
      id: '/_auth/login/sso-callback'
      path: '/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof AuthLoginSsoCallbackRouteImport
      parentRoute: typeof AuthLoginRoute
    }
    '/api/files/$id/download': {
      id: '/api/files/$id/download'
      path: '/download'
      fullPath: '/api/files/$id/download'
      preLoaderRoute: typeof ApiFilesIdDownloadRouteImport
      parentRoute: typeof ApiFilesIdRoute
    }
  }
}

interface AuthLoginRouteChildren {
  AuthLoginSsoCallbackRoute: typeof AuthLoginSsoCallbackRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginSsoCallbackRoute: AuthLoginSsoCallbackRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthSignupRouteChildren {
  AuthSignupSsoCallbackRoute: typeof AuthSignupSsoCallbackRoute
}

const AuthSignupRouteChildren: AuthSignupRouteChildren = {
  AuthSignupSsoCallbackRoute: AuthSignupSsoCallbackRoute,
}

const AuthSignupRouteWithChildren = AuthSignupRoute._addFileChildren(
  AuthSignupRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthSignupRoute: typeof AuthSignupRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthSignupRoute: AuthSignupRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecentRoute: typeof DashboardRecentRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSharedRoute: typeof DashboardSharedRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecentRoute: DashboardRecentRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSharedRoute: DashboardSharedRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiFilesIdRouteChildren {
  ApiFilesIdDownloadRoute: typeof ApiFilesIdDownloadRoute
}

const ApiFilesIdRouteChildren: ApiFilesIdRouteChildren = {
  ApiFilesIdDownloadRoute: ApiFilesIdDownloadRoute,
}

const ApiFilesIdRouteWithChildren = ApiFilesIdRoute._addFileChildren(
  ApiFilesIdRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesIdRoute: typeof ApiFilesIdRouteWithChildren
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesIdRoute: ApiFilesIdRouteWithChildren,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

interface ApiSharesRouteChildren {
  ApiSharesTokenRoute: typeof ApiSharesTokenRoute
}

const ApiSharesRouteChildren: ApiSharesRouteChildren = {
  ApiSharesTokenRoute: ApiSharesTokenRoute,
}

const ApiSharesRouteWithChildren = ApiSharesRoute._addFileChildren(
  ApiSharesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiSharesRoute: ApiSharesRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
